base:
  - pip
  - wheel
  - setuptools
  - colorama
  - PyYAML
  - requests
  - gitpython
  - jinja2
bigquery:
  - dbt-bigquery
  - google-cloud
  - google-cloud-bigquery
  - google-cloud-storage
snowflake:
  - dbt-snowflake
