name: '{{ project }}'
version: '1.2.0'
config-version: 2
profile: '{{ profile }}'

model-paths: ['sources', 'models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['data']
macro-paths: ['macros']
snapshot-paths: ['snapshots']
docs-paths: ["descriptions"]
asset-paths: ["assets"]

target-path: 'target'
log-path: 'logs'
packages-install-path: 'dbt_packages'

clean-targets:
  - 'target'
  - 'logs'
  - 'dbt_packages'

models:
  +persist_docs:
    relation: true
    columns: true
  {{ project }}:
    source:
      +materialized: view
    transformation:
      +materialized: table
    relational:
      +materialized: table
    dimensional:
      +materialized: table
    datamart:
      +materialized: view
    dataset:
      +materialized: view

seeds:
  +persist_docs:
    relation: true
    columns: true

on-run-start:
  - "{% raw %}{{ drop_orphaned_relations() }}{% endraw %}"

on-run-end:
  - "{% raw %}{{ missing_attributes_validation(['source', 'transformation'], false) }}{% endraw %}"
  - "{% raw %}{{ extra_attributes_validation(['source', 'transformation', 'relational_history', 'dimensional_history'], false) }}{% endraw %}"
  - "{% raw %}{{ mismatch_datatype_validation([], false) }}{% endraw %}"
  - "{% raw %}{{ path_structure_validation(false) }}{% endraw %}"
  - "{% raw %}{{ file_naming_validation(false) }}{% endraw %}"

vars:
  local-timezone: 'America/New_York'
  valid-file-naming:
    - description: all lower case with underscores
      regex: '[a-z_/.]+'
    - description: begins with 'sources', lowercase, numbers, or underscores
      regex: '^sources*[a-zA-Z0-9_/.]+'
  managed-schemas:
    - 'audit'
    - 'source'
    - 'transformation'
    - 'relational'
    - 'dimensional'
    - 'datamart'
    - 'dataset'
